### ISSUE TITLE
[Android] UnsatisfiedLinkError: dlopen failed: cannot locate symbol fseeko64

### ISSUE THREAD

**Issue by proninyaroslav** [aldenml/libtorrent4j#158]
I think this error is related to this issue https://github.com/aldenml/libtorrent4j/issues/125

**Library version:**  2.0.2-11
**Android version:** 6.0.1
**Device**: Samsung Galaxy On7
**Arch**:  armeabi-v7a

**Full bug report:** [ACRA-report.txt](https://github.com/aldenml/libtorrent4j/files/5939511/ACRA-report.txt)
**Stack trace:**
```
java.lang.LinkageError: Look for your architecture binary instructions at: https:\/\/github.com\/aldenml\/libtorrent4j
	at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:28)
	at org.libtorrent4j.swig.libtorrent_jni.alert_error_notification_get(Native Method)
	at org.libtorrent4j.swig.alert.<clinit>(alert.java:494)
	at org.libtorrent4j.alerts.AlertType.<clinit>(AlertType.java:11)
	at org.libtorrent4j.SessionManager.<clinit>(SessionManager.java:67)
	at org.proninyaroslav.libretorrent.core.model.TorrentEngine.<init>(TorrentEngine.java:138)
	at org.proninyaroslav.libretorrent.core.model.TorrentEngine.getInstance(TorrentEngine.java:122)
	at org.proninyaroslav.libretorrent.core.model.TorrentInfoProvider.getInstance(TorrentInfoProvider.java:81)
	at org.proninyaroslav.libretorrent.ui.main.MainActivity.onCreate(MainActivity.java:145)
	at android.app.Activity.performCreate(Activity.java:6904)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7331)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fseeko64" referenced by "\/data\/app\/org.proninyaroslav.libretorrent-1\/lib\/arm\/libtorrent4j.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:23)
	... 20 more
```

**Comment by aldenml** [comment]
Totally, working on it already, see also https://github.com/arvidn/libtorrent/issues/5954

**Comment by proninyaroslav** [comment]
Thank you. I also got the error on Nexus 7, 6.0.1.
[ACRA-report.txt](https://github.com/aldenml/libtorrent4j/files/5939526/ACRA-report.txt)

**Comment by aldenml** [comment]
Hi @proninyaroslav, in a few minutes `v2.0.2-12` should be visible in maven, give it a try and let me know if the issue persists (or there is something new instead :)

**Comment by proninyaroslav** [comment]
Thank you, I'll check it soon.

**Comment by proninyaroslav** [comment]
Yes, the problem has been fixed. No other problems have been noticed yet.
