### ISSUE TITLE
Bug: Can't create large torrents

### ISSUE THREAD

**Issue by master255** [aldenml/libtorrent4j#164]
@aldenml  When I create a torrent larger than 2Gb I always get an error:
```
2021-03-03 13:47:00.030 27601-30156 E/AndroidRuntime: FATAL EXCEPTION: Thread-18
    Process: com.media.library, PID: 27601
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 595096 bytes
        at org.libtorrent4j.swig.libtorrent_jni.set_piece_hashes_ex(Native Method)
        at org.libtorrent4j.swig.libtorrent.set_piece_hashes_ex(libtorrent.java:429)
        at org.libtorrent4j.TorrentBuilder.generate(TorrentBuilder.java:469)
        at com.media.library.fragments.PlayerFragment$16.lambda$createTorrent$0$PlayerFragment$16(PlayerFragment.java:5282)
        at com.media.library.fragments.-$$Lambda$PlayerFragment$16$Bx-DssT8DXdkHlD1wM3dKsXC5Sc.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by aldenml** [comment]
ACK, looking into this

**Comment by aldenml** [comment]
Hi @master255, do you attach a listener to the `TorrentBuilder`? If that's the case, can you provide more information on what do you do on `Listener#progress`? (i.e are you communicating via intents with other parts of your application)

**Comment by master255** [comment]
@aldenml Yes. You're right. The problem is that I wanted to display the progress for the user. Apparently there is some bug in this part. After I removed Listener the torrent file is created much faster and there are no problems with creating large torrents.
