### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Viveksaini9898** [aldenml/libtorrent4j#194]
Fatal Exception: java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/aldenml/libtorrent4j
       at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:71)
       at org.libtorrent4j.swig.libtorrent_jni.alert_error_notification_get(libtorrent_jni.java)
       at org.libtorrent4j.swig.alert.<clinit>(alert.java:2)
       at org.libtorrent4j.alerts.AlertType.<clinit>(AlertType.java:2)
       at org.libtorrent4j.SessionManager.<clinit>(SessionManager.java)
       at com.pitorrent.client.torrent.core.model.TorrentEngine.<init>(TorrentEngine.java:76)
       at com.pitorrent.client.torrent.core.model.TorrentEngine.getInstance(TorrentEngine.java:13)
       at com.pitorrent.client.torrent.core.model.TorrentInfoProvider.getInstance(TorrentInfoProvider.java:13)
       at com.pitorrent.client.torrent.ui.main.MainActivity.onCreate(MainActivity.java:48)
       at android.app.Activity.performCreate(Activity.java:7963)
       at android.app.Activity.performCreate(Activity.java:7952)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by aldenml** [comment]
where and how are you running this?

**Comment by Viveksaini9898** [comment]
Brand:samsung
Model:Galaxy A21s
Version:10
libtorrent4j version : 2.0.4-20

**Comment by Viveksaini9898** [comment]
Brand:samsung
Model:Galaxy A21s
Version:10
libtorrent4j version : 2.0.4-20

**Comment by aldenml** [comment]
Can you obtain logs from the phone before this error (since the very beginning of the app start)?

**Comment by aldenml** [comment]
stale, no additional information was provided
