### ISSUE TITLE
java.lang.UnsatisfiedLinkError: libtorrent4j.jar: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by dbwdbw1** [aldenml/libtorrent4j#199]
When I try to run the demo on Window10, it has this error:
java.lang.UnsatisfiedLinkError: libtorrent4j.jar: %1 is not a valid Win32 application.

And when I run the demo on Linux, it has this error:
OpenJDK 64-Bit Server VM warning: You have loaded library /home/hicloud/libtorrent4j-2.0.4-22-RC1.jar which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/hicloud/libtorrent4j-2.0.4-22-RC1.jar: /home/hicloud/libtorrent4j-2.0.4-22-RC1.jar: invalid ELF header (Possible cause: endianness mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.company.Main.main(Main.java:57)

Where is wrong?

**Comment by aldenml** [comment]
How are you specifying the binary location?

**Comment by aldenml** [comment]
stale
