### ISSUE TITLE
[Android] Fatal Exception: java.lang.LinkageError 

### ISSUE THREAD

**Issue by LightningGem** [aldenml/libtorrent4j#253]
device: Galaxy Tab A 8.0
architeture: armeabi-v7a

Fatal Exception: java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/aldenml/libtorrent4j
       at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:28)
       at org.libtorrent4j.swig.libtorrent_jni.settings_pack_num_string_settings_get(libtorrent_jni.java)
       at org.libtorrent4j.swig.settings_pack.<clinit>(settings_pack.java)
       at org.libtorrent4j.swig.libtorrent.default_settings(libtorrent.java:313) 
       
I have following dependencies:
    implementation "org.libtorrent4j:libtorrent4j:$libtorrent4j_version"
    implementation "org.libtorrent4j:libtorrent4j-android-arm64:$libtorrent4j_version"
    implementation "org.libtorrent4j:libtorrent4j-android-arm:$libtorrent4j_version"
    implementation "org.libtorrent4j:libtorrent4j-android-x86_64:$libtorrent4j_version"
    implementation "org.libtorrent4j:libtorrent4j-android-x86:$libtorrent4j_version"

**Comment by phj233** [comment]
hi, I also have this problem, how did you solve it
