### ISSUE TITLE
Fetch v2 Magnet failed

### ISSUE THREAD

**Issue by Jason-wam** [aldenml/libtorrent4j#254]
Fetch V2 Magnet Failed

magnet:?xt=urn:btmh:1220a16218f84fb0b0af5abff0ed33507fcf0a047793d523017f865f5a76713ae31d&dn=Victoria%203%20V1.3.6%E5%85%A8DLC%E5%AD%A6%E4%B9%A0%E7%89%88.zip&xl=7114584386

`
session.fetchMagnet(magnet, timeout, dir)
`

logcat: 

Error building magnet torrent data
      java.lang.RuntimeException: a piece layer is invalid [libtorrent:215]
      at org.libtorrent4j.swig.libtorrent_jni.write_torrent_file_buf_ex(Native Method)
      at org.libtorrent4j.swig.libtorrent.write_torrent_file_buf_ex(libtorrent.java:464)
      at org.libtorrent4j.SessionManager$1.alert(SessionManager.java:671)
      at org.libtorrent4j.AlertMulticaster.alert(AlertMulticaster.java:27)
      at org.libtorrent4j.SessionManager.fireAlert(SessionManager.java:1048)
      at org.libtorrent4j.SessionManager.access$1200(SessionManager.java:49)
      at org.libtorrent4j.SessionManager$5.run(SessionManager.java:1207)

**Comment by aldenml** [comment]
Hi @Jason-wam , thanks or the report. I have been very busy lately, I will look at this as soon as possible

**Comment by chenqinhui** [comment]
hi, any updates on this problem yet? I also stuck into it.
